Repository ant-design/ant-design-icons, pull requests merged in 2019-12, with the labels that each got.

#186 chore: add license
  LICENSE
Labels: chore

#192 optimize: fix docz deps
  packages/icons-svg/package.json
Labels: optimize

#203 feat(icons-svg): use np
  packages/icons-svg/package.json
Labels: enhancement

#204 test: fix test cases
  packages/icons-react/jest.config.js
  packages/icons-react/package.json
  packages/icons-react/tests/Icon.test.tsx
  packages/icons-react/tests/index.test.tsx
  packages/icons-svg/package.json
Labels: test

#199 feat(icons-react): twotone color support array type
  .circleci/config.yml
  package.json
  packages/icons-react/examples/ant-design-twotone-demo.tsx
  packages/icons-react/package.json
  packages/icons-react/src/components/AntdIcon.tsx
  packages/icons-react/src/components/IconBase.tsx
  packages/icons-react/src/components/twoTonePrimaryColor.ts
  packages/icons-react/src/utils.ts
  packages/icons-react/tests/__snapshots__/index.test.tsx.snap
  packages/icons-react/tests/index.test.tsx
Labels: enhancement

#213 hotfix: rollback to old icon list
  packages/icons-svg/build/constants.ts
Labels: hotfix
