Repository ant-design/ant-design-icons, pull requests merged in 2019-11, with the labels that each got.

#168 deps(module:angular): update to 9.0.0
  packages/icons-angular/angular.json
  packages/icons-angular/build.sh
  packages/icons-angular/build/copy.ts
  packages/icons-angular/examples/tsconfig.app.json
  packages/icons-angular/lib/component/icon.module.ts
  packages/icons-angular/lib/component/icon.service.ts
  packages/icons-angular/lib/package.json
  packages/icons-angular/lib/tsconfig.lib.json
  packages/icons-angular/lib/tsconfig.lib.prod.json
  packages/icons-angular/lib/tsconfig.spec.json
  packages/icons-angular/package.json
  packages/icons-angular/tsconfig.json
Labels: dependencies

#175 fix(icons-react): lint issues
  packages/icons-react/src/components/Icon.tsx
  packages/icons-react/src/utils.ts
Labels: build

#174 fix: change inset styles precedence
  packages/icons-react/src/utils.ts
Labels: bug

#176 fix: lint issue from pr 174
  packages/icons-react/src/utils.ts
Labels: bug

#177 test: add style precedence test
  packages/icons-react/jest.config.js
  packages/icons-react/tests/iconStyles.test.tsx
Labels: test

#180 doc: update readme
  packages/icons-react/README.md
Labels: doc
